name: Build

on:
    pull_request:
        paths-ignore:
            - "adr/**"
            - "docs/**"
            - "*.md"
    workflow_dispatch: ~
    push:
        branches-ignore:
            - 'dependabot/**'
            - 'upmerge/**'

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}-minimal
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    static-checks:
        name: Static checks
        uses: ./.github/workflows/ci_static-checks.yaml
        with:
            type: minimal
    e2e-mysql:
        name: End-to-end tests (MySQL)
        needs: static-checks
        uses: ./.github/workflows/ci_e2e-mysql.yaml
        with:
            type: minimal
